INSERT INTO `music_store`.`products`
(`name`,`description`,`image_url`,`price`,`rate`,`url_video`,`instrument_id`,`manufacturer_id`)
VALUES
("Yamaha C80",
"La C80 è una delle chitarre classiche Yamaha meno costose, ma qualità e sonorità sono eccezionali. Ottima per principianti e giovani musicisti.
","https://www.ciaravola.it/33577-large_default/yamaha-c80-ii.jpg","229,00",4,"https://www.youtube.com/watch?v=sopEVRAu3_U","1","1"),
("Yamaha NCX3 NT",
" La rinomata maestria Yamaha si traduce in strumenti con suono e suonabilità eccezionali - e quattro modelli incorporano il sistema di pickup Atmosfeel che non ha rivali, con un suono eccezionale indipendentemente dal livello del volume. Con le eleganti forme del body a spalla mancante, le piacevoli scelte dei legni, i motivi della rosetta colorati e gli abbellimenti di buon gusto, le chitarre della serie NX sono progettate per i musicisti contemporanei che cercano la perfetta combinazione di comfort e stile. Come risultato di misurazioni e sperimentazioni precise, sono stati apportate numerose modifiche che migliorano la risposta a bassa frequenza senza compromettere il sustain. Questi cambiamenti sono stati ulteriormente perfezionati per enfatizzare le caratteristiche naturali di legni specifici ed ottimizzati per ogni formato del corpo. Il sistema di pickup Yamaha Atmosfeel offre un suono amplificato senza pari anche a volumi da performance. Un pickup piezoelettrico sottosella con sensori singoli per corda cattura solo le frequenze medio-basse (eliminando la caratteristica fragilità dei pickup piezoelettrici), mentre un trasduttore sintetico unico cattura gli alti ed un microfono interno cattura la risonanza e la "'ariosità'" del body",
"https://www.discoservicemusicheria.eu/wp-content/uploads/2021/10/Yamaha-NCX3-Electro-Nylon-String-Natural.jpg",
"959.00",
5,
"https://www.youtube.com/watch?v=YMtLuY6vHM8",
"1",
"1"),
("Steinway & Sons B-211",
"Il modello B-211 è spesso definito come il “pianoforte a coda perfetto”. Esigenti pianisti, amatoriali e professionisti, ma anche le istituzioni, conoscono il valore di questo strumento. Grazie alla ricca scala delle sfumature timbriche ed il suono pieno d'anima si trova ai primi posti della gamma dei prodotti di Steinway & Sons.",
"https://eu.steinway.com/fileadmin/user_upload/Fluegel_B_Black_03.jpg",
"55800",
5,
"https://www.youtube.com/watch?v=BjMDYUxrLVA",
"4",
"10"),
("Kawai KDP120 Black Satin",
"Kawai presenta il KDP 120, il successore del popolare CN17. La già convincente tastiera "'Responsive Hammer Compact II'" del CN17 è stata adottata e ottimizzata dal suo successore: il KDP 120 è dotato di un migliore materiale di smorzamento per un suono ancora più fluido. Campioni di alta qualità, incluso il suono del pluripremiato pianoforte a coda da concerto Shigeru Kawai SK-EX, forniscono una sensazione di esecuzione impressionante, mentre la nuova funzione "'Low Balance Volume'" del KDP 120 regola in modo intelligente il volume per suono a basso volume. Di particolare interesse è anche l'implementazione di USB-MIDI e Bluetooth-MIDI, che consentono il collegamento con le app avanzate di Kawai "'PianoRemote" e "PiabookPlayer'". Queste app ti consentono di selezionare e modificare suoni, impostazioni ed i brani delle lezioni con estrema precisione.",
"https://www.bananamusic.it/279331-large_default/kawai-kdp120-black-satin.jpg",
"1289",
5,
"https://www.youtube.com/watch?v=O_G_ObU1dfM",
"5",
"9"),
("Gibson SG Standard Bass Ebony",
"L'SG Bass ha l'aspetto, il suono ed il feel leggendari che lo hanno reso uno dei bassi Gibson più iconici. La lunghezza della scala ridotta è in realtà una parte importante di questo suono! Sebbene la lunghezza ridotta della scala dell'SG Bass sai preferita dai musicisti più piccoli, è preferita da molti anche per il potente suono fondamentale per cui questo basso in scala ridotta è noto. Come ci si aspettava, il body in mogano presenta scarf profondamente scolpiti, il manico in mogano dal profilo arrotondato e la tastiera in palissandro sono familiari e comodi. Una coppia di pickup per basso SG calibrati (manico e ponte) con volumi indipendenti ed un controllo del tono master aggiungono ulteriori possibilità sonore.",
"https://d1aeri3ty3izns.cloudfront.net/media/46/468743/600/preview.jpg",
"1439,00",
5,
"https://www.youtube.com/watch?v=VokMBpEIJOs",
"12",
"3"),
("Gibson Thunderbird Bass Tobacco Burst",
"Gibson Thunderbird ha il classico design del body e della paletta invertite, originariamente introdotte nel 1963 come primo design dei bassi a manico neck-through di Gibson. Il tradizionale manico in mogano / noce a 9 strati offre una risposta di fascia bassa fragorosa e un sustain da pianoforte. La larghezza ridotta del capotasto e il profilo arrotondato del manico rendono lo stesso veloce e intuitivo. I pickup humbucking (manico e ponte) del Thunderbird ad output elevato con magnete ceramico offrono l'iconica fascia bassa per la quale è noto Thunderbird. Disponibile in 2 finiture classiche: Tobacco Burst ed Ebony.",
"https://d1aeri3ty3izns.cloudfront.net/media/46/465375/600/preview.jpg",
"1949,00",
"",
"https://www.youtube.com/watch?v=4rdehWSbFSY",
"12",
"3"),
("Richwood RMA-110-VS A-Style",
"L'RMA-110-VS ha il suono e il vero taglio che ogni appassionato di bluegrass abbraccerà. Il manico, i lati ed il fondo in acero fiammato, è una vera gioia per gli occhi. La suonabilità di tutti gli strumenti della serie Master è garantita dal setup professionale in laboratorio.
Caratteristiche",
"https://thumbs.static-thomann.de/thumb/padthumb600x600/pics/bdb/519457/17335569_800.jpg",
"428",
"",
"https://www.youtube.com/watch?v=bdgtfCrfk9s",
"13",
"6"),
("Richwood RMB-604-SS",
"Questo banjo tenore Richwood Master Series a 17 tasti è popolare principalmente nella musica tradizionale irlandese. La versione a 17 tasti ha un suono più vellutato e dolce rispetto alla sua controparte a 19 tasti. Lo stile di esecuzione tipico di un banjo tenore è con un plettro, ma ovviamente su questo strumento ti incoraggiamo a esplorare tutte le tecniche. Come con tutti i banjo della serie Master, l'RMB-604-SS è uno strumento molto stabile con 24 staffe, legno e parti di qualità, che garantiscono una vita di piacere musicale.",
"https://files.ekmcdn.com/4e32fa/images/richwood-rmb-604-master-series-tenor-banjo-4-string-3739-p.jpg?v=0F716607-88A7-43A5-93C6-76E64983B4B8",
"319",
"",
"https://www.youtube.com/watch?v=sJCDBFPvXqw",
"14",
"6"),
("Pearl Roadshow Junior Jet Black",
"Il Pearl Roadshow Junior 5pc Complete Tamburo Kit ispira divertimento e creatività senza fine e svilupperà la coordinazione, la disciplina e la concentrazione del tuo bambino. Il tutto mentre si divertono e imparano uno strumento.
Ridimensionato per soddisfare i più piccoli, il Roadshow Junior è la dimensione perfetta per i giovani batteristi. Viene dotato di tutto il necessario per iniziare a suonare: Bacchette, pedale, sgabello, piatti charleston, supporti per piatti e tutta la batteria necessaria per suonare al meglio. È conveniente ed è di una marca rinomata; il vero pacchetto per iniziare il tuo viaggio nel ritmo con stile.",
"https://www.fireflyaudio.it/wp-content/uploads/2021/02/pearl-junior-g.png",
"409",
5,
"https://www.youtube.com/watch?v=4mqYcD-4A7w",
"11",
"18"),
("Yamaha SBP2F5 Stage Custom Birch",
"Così come accadde con l'introduzione della Stage Custom nel 1995, YAMAHA definisce nuovamente gli standard di valore e suono. La nuova Stage Custom eredita fusti in legno di betulla al 100%, con hardware migliorato. Il fusto è un fattore chiave nella capacità di un tamburo di "'rimbombare'", o risuonare. Di conseguenza, la Stage Custom impiega il 100% di Betulla - un classico nel campo dei drum kit di alta classe. Inoltre, con la sua struttura a sei strati, la Stage Custom trasmette con precisione le vibrazioni prodotte sulla superficie d'impatto, ottenendo prestazioni che travolgono qualunque cosa nella stessa categoria.",
"https://drumcentral.s3.eu-west-2.amazonaws.com/media/2022/10/24155456/Yamaha-Stage-Custom-Natural-Wood-1.jpeg",
"769",
5,
"https://www.youtube.com/watch?v=KxS9on7ZBzA",
"11",
"1"),
("Stentor Verona Kit Violino",
"Il Kit Violino Stentor Verona offre tutto il necessario per il musicista intermedio. La Tastiera in ebano offre suonabilità confortevole con coerenza su tutta la superficie. La forma ad arco del corpo produce una gamma di frequenza dinamica e capacità di volume alto. La cordiera Wittner e Ponte Aubert mantengono la stabilità dell'accordatura e intonazione completamente stabile. Questo Kit comprende anche un arco in Paubrasilia con intarsi perlati e una custodia leggera.",
"https://d1aeri3ty3izns.cloudfront.net/media/49/494652/1200/preview.jpg",
"583",
5,
"https://www.youtube.com/watch?v=eh398ykycYU",
"9",
"12"),
("Stentor Arcadia Violin",
"Eccellenza artigianale. Il violino Stentor Arcadia è uno dei migliori violini che Stentor ha da offrire. Vantando un corpo intagliato a mano dai legni più selezionati e altamente figurati, il violino Stentor Arcadia è la scelta ideale per gli studenti che avanzano.
Ciò che rende davvero il violino Arcadia si distinguono è come è fatto. Realizzato a mano da un artigiano altamente qualificato, ogni Arcadia è uno strumento unico che riflette l'individualità del suo maestro. Una volta finito, il violino Arcadia è rifinito con una splendida vernice di gommalacca.",
"https://d1aeri3ty3izns.cloudfront.net/media/57/578358/1200/preview_1.jpg",
"812",
5,
"https://www.youtube.com/watch?v=l0SJ2muDXvo",
"9",
"12"),
("Fender Player Stratocaster PF 3",
"Il suono ispiratore di una Stratocaster è uno dei fondamenti Fender. Caratterizzato da un suono classico, high-end squillanti, medi potenti ed una fascia bassa robusta, abbinato ad una articolazione cristallina, la Player Stratocaster è dotata dello stile e del feel Fender autentico. E' pronta a servire la tua visione musicale, è abbastanza versatile da gestire qualsiasi stile ed è la piattaforma perfetta per creare il tuo suono. Rompendo con la tradizione, Fender ha aggiunto un controllo del tono dedicato per il pickup al ponte, dandoti un maggiore controllo sul suono nelle posizioni del pickup 1 e 2.",
"https://www.tomassone.it/media/catalog/product/cache/4/image/9df78eab33525d08d6e5fb8d27136e95/P/R/PRO_FENPLASTRPFSB_01.jpg",
"715",
5,
"https://www.youtube.com/watch?v=6nCGeEAghO8",
"2",
"2"),
("Ibanez GSR200 Black",
"Per 25 anni i bassi SR hanno dato ai bassisti una moderna alternativa. Con la sua persistente popolarità, Ibanez è costantemente alla ricerca di rispondere alle esigenze di una gamma di musicisti più ampia, con diversi budget. L'SR continua ad emozionare con il suo manico veloce, il body leggero ed un elettronica perfettamente abbinata.",
"https://d1aeri3ty3izns.cloudfront.net/media/61/617105/600/preview.jpg",
"275",
5,
"https://www.youtube.com/watch?v=nC7SyuNMDuM",
"12",
"4"),
("Yamaha YTR-4335 GII",
"La tromba YTR-4335GII, pur mantenendo lo stesso design di base del modello di grande successo YTR-4335G, offre alcuni miglioramenti in termini di suonabilità e di potenza sonora. La serie 4000 è ora disponibile con una versione modificata della campana in Gold Brass in 2 pezzi con uno spessore di metallo ottimale, migliorando in questo modo sia il suono che la suonabilità. I pistoni in monel altamente resistenti, nonchè i nuovi tappi e bottoni superiori e inferiori, aiutano ad allungare la vita dello strumento e allo stesso tempo ad ottimizzare la qualità del suono.",
"https://www.fireflyaudio.it/wp-content/uploads/2020/01/YAMAHA-YTR4335-GII.jpg",
"740",
5,
"https://www.youtube.com/watch?v=L2XnY-nmoVU",
"7",
"1"),
("Yamaha PSR-SX900",
"La PSR-SX900 è dotata del contenuto della workstation digitale Genos ammiraglia di Yamaha. Questo contenuto premium suona in modo sorprendente grazie al sistema di altoparlanti bi-amplificato all'avanguardia con la sua ampia immagine stereo. Naviga rapidamente e facilmente utilizzando il luminoso touchscreen TFT a colori da 7 o imposta i pulsanti assegnabili per accedere istantaneamente alle tue funzioni preferite. Yamaha ha dotato la Yamaha di altre nuove funzionalità, tra cui un joystick controller, Chord Looper, nuova struttura di insert degli effetti, sezione Style reset, una nuova action della tastiera Yamaha con un fantastico feeling e molto altro. Ogni grande canzone inizia come un idea: una semplice melodia o un ritmo che si perfeziona con l''accompagnamento e si organizza in un pezzo finito. Con una workstation arranger Yamaha PSR-SX900, troverai quel processo magico più fluido e intuitivo che mai.",
"https://www.davolimusic.it/image/cache/catalog/YAMAHA%20KEYBOARDS/PSR%20SX900-1000x1000w.jpg",
"2359",
5,
"https://www.youtube.com/watch?v=IjZaVx9-Xlc",
"6",
"1"),
("Mapex Tornado 5294 Pop/Rock Black",
"Le batterie Mapex della serie Tornado sono dotate di fusti realizzati in Tiglio e di hardware rinforzato con cassa ad otto blocchetti, tom a sei blocchetti e piedini della cassa telescopici. Tutti i kit includono rullanti Tornado in legno dello stesso colore della batteria, e vengono venduti completi di Charleston 14" 'e di Crash da 16'". Questa batteria unisce una solida costruzione ad una resa sonora splendida, rendendola un ottimo acquisto per i principianti.",
"https://www.ringomusic.net/wp-content/uploads/2022/06/23976-1.jpg",
"499",
4,
"https://www.youtube.com/watch?v=rFIvFedeMKE",
"11",
"20"),
("Pearl Export EXL American Fusion Drum Kit",
"Il Pearl EXL 22 American Fusion 5pc Tamburo Kit è tornato e meglio che mai, dando qualsiasi studente batterista un forte inizio alla loro vita di batteria. I suoi gusci sono fatti di 6 strati di pioppo miscelato e mogano asiatico per fornire il perfetto equilibrio di vibrazione e risonanza, mentre i piatti inclusi Sabian SBR sono durevoli e versatili, con un tono ben arrotondato e attacco veloce.",
"https://d1aeri3ty3izns.cloudfront.net/media/73/733582/600/preview.jpg",
"1003",
5,
"https://www.youtube.com/watch?v=eFo1l5GV8ds",
"11",
"18"),
("Primavera 200 Violin",
"Iniziate a imparare il violino con fiducia! Il violino Primavera 1/2 200 si distingue come Primavera definitivo vestito studente grazie alla costruzione di alta qualità e il cartellino del prezzo competitivo. È stato anche votato il Miglior strumento ad arco per due anni di fila, quindi sai che sarà buono!
Simile ad altri strumenti Primavera, il violino 200 è stato costruito con studenti e principianti in mente. Vantando un corpo in acero e abete rosso intagliato a mano, il violino Primavera produce un tono straordinariamente ben arrotondato. E una volta combinato con i raccordi ebony, inizierete a rendervi conto di quanto sia buono il violino 200.",
"https://d1aeri3ty3izns.cloudfront.net/media/21/217293/1200/preview_3.jpg",
"208",
"",
"https://www.youtube.com/watch?v=zuQzl-IKves",
"9",
"13"),
("Kawai Shigeru SKEXL",
"Il lavoro manuale di alta precisione, l'uso di materiali scelti appositamente e innovazioni esclusive garantiscono la rarità e l'unicità di ogni pianoforte SHIGERU KAWAI. Scelti dalle più grandi istituzioni e sale da concerto del mondo, celebrati dagli artisti più rinomati, utilizzati in rinomati concorsi internazionali, i pianoforti SHIGERU KAWAI ispirano passione creativa e celebrano la gioia e la condivisione di emozioni musicali.",
"https://www.musique-shop.fr/it/pub/media/catalog/product/cache/31dab2e2e3e2acd84373ef0ae9d96204/c/2/c21-skexl.png",
"143123",
"",
"https://www.youtube.com/watch?v=WCqlYvjv8x4",
"4",
"9"),
("Stentor Student I SR 1102 Cello 4/4",
"Violoncello 4/4 da studio compreso di borsa imbottita, archetto e ponte.",
"https://thumbs.static-thomann.de/thumb/padthumb600x600/pics/bdb/137936/8270218_800.jpg",
"219",
"4",
"https://www.youtube.com/watch?v=iut9YqBNepo",
"10",
"12");
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
""),
("",
"",
"",
"",
"",
"",
"",
"");
