INSERT INTO `music_store`.`artists`
(`first_name`,
`last_name`,
`country`,
`history`,
`cover_image`,
`image_url`,
`spotify_url`)
VALUES
("Alan",
"Gogoll",
"Australia",
"Alan Gogoll è un chitarrista e compositore acustico australiano noto soprattutto per l'invenzione della sua tecnica di armoniche artificiali simultanee a due mani che ha chiamato Bell Harmonics, che è presente in molte delle sue canzoni originali come Mulberry Mouse, Pepperleaf Pipes, Through the Foglie e Armonica di Bell. La sua passione per la chitarra è iniziata da bambino, sviluppando la sua arte nel corso degli anni, sperimentando con la sua amata chitarra Åstrand per creare le sue tipiche armoniche a campana. Le sue abilità di chitarrista non sono passate inosservate, con la sua serie Stringscape su YouTube che fa luce sul suo design innovativo. Costruendo una chitarra personalizzata e un impianto fotografico per catturare le vibrazioni delle corde della sua musica dall'interno della chitarra mentre si guardano paesaggi tranquilli, i suoi video hanno abbracciato milioni di spettatori.
Ma non è solo il mondo online in cui Alan Gogoll è fiorito, la sua stravagante musica folk lo ha visto fare tournée in tutto il mondo, dalle sale da concerto di Parigi a Pechino, da Osaka a Göteborg. Trascorrendo gran parte del suo tempo all'estero, Gogoll si è ritrovato nella sua terra natale, l'Australia, prima che arrivasse il COVID-19.
Sebbene la pandemia abbia limitato le sue esibizioni musicali, ha colto l'occasione per trascorrere del tempo con i propri cari e dedicarsi a nuovi progetti, tra cui il suo ultimo album in studio Turtlebank Tales. Registrato dallo stesso Gogoll in uno studio improvvisato, l'album è stato pubblicato nel alla fine del 2021, e racconta la storia di creature del bosco che si radunano sulla sponda di un fiume. L'album cattura l'essenza della meraviglia e dell'immaginazione infantile raccontate attraverso delicati fraseggi melodici e armoniche uniche.
Over the years, Alan Gogoll’s craftsmanship has earned him an array of awards where he was recently named Acoustic Guitarist of the Year by Guitar World and Guitar Player Magazine.",
 "https://images.squarespace-cdn.com/content/v1/5f5bcbf51c22302230cc46ad/1600339477230-GMG9JWSQJFW4E9VFFGAP/Handmade+guitar",
"http://static1.squarespace.com/static/5e604fe08a3a32751ff1e388/t/5f2772ef0ddf0c536e5eafcb/1617592297770/Alan+Gogoll2.jpg?format=1500w",
"https://open.spotify.com/artist/7MOxmVjcx5HWoEu9pBWXT3?si=NMBb7bWiTE2y5xuSlgun3A"),
("John",
"Butler",
"Australia",  
"Nato in California il 1° aprile 1975 da padre australiano e madre americana, Butler emigra in Australia nel 1986 dopo il divorzio dei genitori, col padre, il fratello e la sorella. A 16 anni inizia a suonare la chitarra dobro del nonno. Lascia l’università per dedicarsi alla musica, si esibisce come artista di strada e nel 1996 riunisce le sue canzoni nell’audiocassetta SEARCHING FOR HERITAGE che vende la cifra ragguardevole di 3000 copie. Viene notato da Phil Stevens, proprietario di Mojos, un club di North Fremantle, che ne diventa il manager. Con l’incontro col bassista Gavin Shoesmith e il batterista Jason McCann nasce il trio che debutta nel 1998 con l’album omonimo JOHN BUTLER. La formazione si presenta come John Butler Trio nel 2001, all’epoca della pubblicazione di THREE, vincitore di un ARIA Award (i Grammy australiani) come migliore album indipendente. Se ne accorgono anche i discografici dell’americana ATO, che ripubblicano il lavoro per gli Stati Uniti. Le esibizioni al Bonnaroo, al South By Southwest e come supporter di Dave Matthews Band e John Mayer regalano la popolarità internazionale al gruppo, che dà alle stampe il disco dal vivo LIVING 2001-2002. Come i dischi seguenti, è pubblicato dall’etichetta fondata da Butler e dai membri dei Waifs, la Jarrah. Va ancora meglio il successivo SUNRISE OVER SEA, primo nella classifica australiana, che vede il gruppo in una nuova formazione con Shannon Birchall (contrabbasso) e Nicky Bomba (batteria; è il cognato di Butler, presto sostituito da Michael Barker).
L’intensa attività concertistica è testimoniata dal doppio cd con dvd LIVE AT ST. GALLEN registrato in Svizzera nel 2005. L’album di inediti GRAND NATIONAL esce nel 2007: è una mossa ambiziosa, un disco musicalmente ricco inciso con l’aiuto di Mario Caldato Jr, produttore già al fianco dei Beastie Boys. Dopo l’esibizione al Live Earth dell’estate 2007 e la vittoria di due ARIA Awards, nel 2008 il trio è in giro per gli States con G Love And Special Sauce. Un’epoca si chiude nel 2009 con la separazione da Birchall e Barker, sostituiti rispettivamente da Byorn Luiters e dal figliol prodigo Nicky Bomba.
Nel 2009 Butler partecipa al reality “Who do you think you are?”, basato sulla ricerca dei propri antenati, e incide con la nuova formazione APRIL UPRISING (2010), altro numero uno in Australia. Registrato nel 2010 e pubblicato nel 2011, il doppio live americano LIVE AT RED ROCKS sancisce il rinnovato successo del trio, che nell’estate 2013 cambia line-up: fuori Bomba, dentro Grant Gerathy. Quando accade, la registrazione del nuovo album FLESH & BLOOD (2014) è sostanzialmente ultimata e Gerathy vi appare in una sola canzone. (30 giu 2014)",
"https://img.freepik.com/free-photo/acoustic-guitar-closeup-with-copy-space_169016-3346.jpg?w=900&t=st=1678725712~exp=1678726312~hmac=1361150453e7a00cefcdeccf07e59e6d58e2401354c22c005edcbeedc3167c03",
"https://dice-i-scdn-co.imgix.net/image/ab6761610000e5ebd8787111a919c381c74ab26e",
"https://open.spotify.com/artist/6fBF4MULW5yMzyGaon1kUt?si=p16tKR-CTuKfWSHYa8RuaQ"),
("Steph",
"Strings",
"Australia", 
"In tenera età, Steph ha scoperto il suo interesse per la musica. Sebbene sappia suonare vari strumenti musicali, è specializzata in chitarra. Il suo modo di suonare la musica attraverso la chitarra può attirare il cuore di chiunque. Ama suonarla sui brani con la sua chitarra e caricarla sui social media.
Una delle sue cover è diventata virale nel 2019. Subito dopo, ha iniziato a caricare i suoi video musicali su Instagram. Ora è diventata una star di Instagram notevole. Ed è anche un'ispirazione per le ragazze che vogliono suonare la chitarra e intraprendere la carriera di chitarrista.",
 "https://img.freepik.com/free-photo/acoustic-guitar-closeup-colored-background-flat-lay_169016-23218.jpg?w=1060&t=st=1678726073~exp=1678726673~hmac=bc9004b8b4c70273257e67f13d5d71a443b122773b2fa467d42af3881521808d",
"https://s3-us-west-1.amazonaws.com/wasserman-media-library/music_artists/steph-strings-20220720.jpg",
"https://open.spotify.com/artist/39qxIdIb1R6se4J3X6nRPB?si=_RnNV5kHRxaCe7NFqKWVnw"),
("Jimi",
"Hendrix",
"Inghilterra",
 "James Marshall Hendrix, nato il 27 novembre 1942 a Seattle, è stato considerato all'unanimità il più grande chitarrista elettrico di tutti tempi. Dal suo strumento d'elezione seppe trarre un'innumerevole quantità di diversi effetti timbrici, giungendo a suonarlo anche con i denti , con il gomito o con l' asta del microfono, in modo coerente al carattere istintivo ed esibizionistico dei suoi concerti.
Frutto di un incrocio fra sangue indiano Cherooke, nero e messicano, il geniale musicista vive i suoi primi anni di vita immerso in una situazione familiare non delle più felici. Per anni convive con la nonna (indiana Cherooke purosangue che lo porta ancora più vicino alle sue radici Indiane e ribelli), mentre padre e madre si arrangiano in mille lavori.
All'età di soli dodici anni riceve come dono la sua prima chitarra elettrica, chiamata da lui affettuosamente "'Al'", un piccolo strumento con cui comincia le sue prime esperienze musicali da autodidatta.
I problemi cominciano da lì a poco. La madre muore quando Jimi ha solo quindici anni mentre all'età di sedici viene espulso da scuola, probabilmente per motivi razziali (ci troviamo nell'America puritana e Maccartista degli anni '50). Di fatto comincia a darsi al vagabondaggio, guadagnandosi da vivere con gruppi di rhythm and blues e di rock'n'roll. Dopo aver prestato servizio militare come paracadutista, a ventun'anni si inserisce nel giro dei session-man, ossia di coloro che vengono pagati a cottimo per le loro prestazioni musicali.
Grazie alle sue doti straordinarie nel giro di poco tempo diventa il chitarrista nientemeno che di personlità come Little Richard, Wilson Pickett, Tina Turner e King Curtis, alcune delle stelle del firmamento rock dell'epoca.
Nel 1965 al Greenwich Village forma il suo primo complesso stabile, ottenendo un contratto per esibirsi regolarmente. Con una situazione più sicura alle spalle ha modo di concentrarsi ancora di più nello studio della tecnica esecutiva, in cui arriva a vertici difficilmente avvicinabili - non tanto per la tecnica in sé, quanto per le capacità raggiunte nel trattamento del suono o della singola nota: in questo avvicinandosi, seppur intuitivamente, agli approdi della musica colta del Novecento.
L'innovativo stile di Hendrix nel combinare distorsioni lancinanti, piene di dolore, ad una pura vena blues crea di fatto una nuova forma musicale, che si avvale di tutta la tecnologia legata allo strumento - dal finger-picking al wah-wah, dal plettro ai pedali, dal feedback all'effetto Larsen, dai controlli di tono ai distorsori. Nei suoi brevi quattro anni di "'regno'", Jimi Hendrix amplia il vocabolario della chitarra elettrica rock più di qualsiasi altro. Hendrix diventa un maestro nel riuscire a tirar fuori dalla chitarra suoni mai ascoltati prima di allora; spesso con esperimenti di amplificazione che portano al limite, se non oltre, le capacità delle attrezzature impiegate.
Le sue esibizioni si distingono per la selvaggia energia del suo modo di suonare e per l'irresistibile carica sessuale dei suoi atteggiamenti (il tutto, anche abbondantemente condito da acidi e sostanze psicotrope
Ad ogni modo, se non fosse stato per le interessate cure di Chas Chandler, ex-Animals, manager a New York in cerca di nuovi talenti, forse Hendrix sarebbe solo uno dei tanti nomi che circolavano nell'ambiente, oscurati dai giovani talenti bianchi a cui tanta attenzione poneva l'opinione pubblica ed i media in genere.
Chandler lo porta invece con sé a Londra dove gli procura una sezione ritmica: la nuova band di Jimi, chiamata significativamente "'The Jimi Hendrix Experience'" (formata dal batterista Mitch Mitchell e dal bassista Noel Redding), diventa in breve tempo l'argomento di conversazione principale a Londra nel periodo conclusivo del 1966. Inoltre, il primo singolo dell'Experience, "'ey Joe'", rimane nelle classifiche inglesi per dieci settimane, raggiungendo la sesta posizione nel tardo 1967. Il singolo del debutto è velocemente seguito dal lancio dell'LP "'Are You Experienced?'", una compilation psichedelica zeppa di inni generazionali. L'LP non a caso rimane uno dei più popolari album rock di tutti i tempi, con canzoni immortali quali "'Purple Haze'", "'The Wind Cries Mary'", "'Foxy Lady'", "'Fire'" e "'Are You Experienced?'".
Nonostante lo schiacciante successo della Hendrix Experience in Inghilterra, è solo quando questa, nel giugno del 1967, torna in America infiammando letteralmente la folla del Monterey International Pop Festival che diviene la band più popolare del mondo. Al termine della sua estenuante esibizione (con una versione demoniaca di "'Wild thing'"), dopo aver dato fuoco alla chitarra, Jimi raccoglie un'ovazione interminabile.
Il successivo LP sfornato dalla bande è "'Axis: Bold As Love'" mentre, dopo preso il totale controllo della band e aver trascorso parecchio tempo nella console in studio, nel 1968 è la volta di "'Electric Ladyland'", un capolavoro della storia del rock (malgrado il "'vero'" Jimi Hendrix sia ascoltabile, è bene ricordarlo, solo attraverso le registrazioni dal vivo).
Ma già nel 1968 comincia il declino fisico, morale e artistico di Hendrix. Durante tutto quel fatidico anno le richieste pressanti di concerti e registrazioni in studio snervano notevolmente la fibra del gruppo, tanto che nel 1969 l'Experience si scioglie, forse anche sotto le pressioni del movimento nero delle "'Black Panther'", a cui Hendrix aveva aderito, che disdegnava l'appartenenza di Hendrix ad un trio composto da bianchi.
Ad agosto trionfa a Woodstock, oltre che con la solita infiammata esibizione, anche con una versione delirante dell'inno americano ("'Star spangled banner'"), uno sberleffo divenuto celeberrimo. Con la sua chitarra Hendrix non si limita a distorcere la celebre melodia ma, in linea col pacifismo e le contestazioni del tempo, imita il suono di spari e bombardamenti, ricordando a tutti che era in corso la tragica guerra del Vietnam.
Il 1969 ha inizio con una nuova collaborazione tra Jimi, Billy Cox e il batterista Buddy Miles (tutti musicisti neri), i quali danno vita alla "'Band of Gypsys'". I tre intraprendono una serie di performance stellari nei giorni tra il 31 dicembre 1969 e 1 gennaio 1970. Di questi concerti vengono effettuate delle registrazioni poi messe sul mercato a partire dalla metà degli anni '70 in un unico album.
Successivamente Jimi ricontatta il batterista Mitch Mitchell e, insieme al bassista Billy Cox, rimette in piedi la Jimi Hendrix Experience. In studio il gruppo registra molte tracce per un altro LP, provvisoriamente intitolato First Rays Of The New Rising Sun.
Sfortunatamente Hendrix non riuscirà a veder pubblicato questo nuovo lavoro: un mese dopo, a 28 anni non ancora compiuti, viene ritrovato morto a Londra riverso sul letto di una stanza del Samarkand Hotel, soffocato nel proprio vomito per una overdose di barbiturici. È il 18 settembre 1970.
Da allora è stato un susseguirsi di omaggi alla sua memoria, ma anche di insinuazioni sulla sua morte, considerata misteriosa, un po' come succede a tutte le rockstar scomparse prematuramente. Intorno al patrimonio di Hendrix, com'era prevedibile, si è scatenato un vespaio di beghe legali e di operazioni speculatrici.
Come in vita, anche dopo la morte il grande chitarrista nero è stato manipolato da impresari senza scrupoli. Hendrix è stato indubbiamente uno degli artisti più sfruttati dall'industria discografica, che non esitò (e non esita tuttora) a pubblicare tutto ciò che egli suonò.
Nessuno sa come si sarebbe evoluta la stella di Hendrix, né che percorso avrebbe seguito la sua parabola. Stimato da tutti i veri musicisti, poco prima della sua morte circolava la voce di una sua possibile collaborazione con un altro genio: Miles Davis.
Come scrive il critico Paolo Galori, l'ultimo Hendrix è un musicista solo e visionario, pronto a volare ancora più in alto, fino a bruciarsi le ali, distrutto dagli eccessi nel disperato tentativo di non replicare se stesso di fronte a chi gli chiede prove della sua divinità.",
 "https://images.pexels.com/photos/63695/pexels-photo-63695.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
"https://i.discogs.com/B4BVnJTfrOOOKJtor8YQ9ERIpBsl_e54_RzQqKSawtM/rs:fit/g:sm/q:90/h:450/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTExMDU5/My0xNjM4MjA5OTI2/LTM1ODIuanBlZw.jpeg",
"https://open.spotify.com/playlist/2JRXnerNyzSs7W7eOpYvU3?si=aac30579f5194c98"),
("Ludovico",
"Einaudi",
"Italia", 
 "Ludovico Einaudi nasce a Torino nel 1955, sin dall’infanzia dimostra le sue capacità in campo artistico studiando al conservatorio. Agli inizi della sua carriera si specializza come compositore classico e soltanto negli anni avvenire inizia ad incorporare altri generi all’interno delle sue composizioni. Per la sua bravura viene notato e per questo motivo le sue composizioni vengono utilizzate come colonne sonore di alcuni noti film, basti pensare alla pellicola Quasi amici, in cui è presente l’opera musicale di Einaudi. Ludovico Einaudi ha anche composto numerosi album da solista e altrettante in collaborazione con altri artisti del suo calibro. Per tali motivi questa figura è considerata come una delle più importanti promesse della musica italiana grazie alla sua abilità di fondere differenti stili artistici adattandoli a basi prevalentemente classiche. Tutti hanno almeno una volta ascoltato una delle composizioni realizzate da Ludovico Einaudi emozionandosi intensamente; infatti l’idea alla base della sua arte consiste nel trasmettere un messaggio che possa raggiungere gli animi di tutti coloro che la ascoltano.",
"https://images.pexels.com/photos/159420/piano-instrument-music-keys-159420.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
"https://ludovicoeinaudi.com/wp-content/uploads/2022/08/494cRayTarantino_Web-e1660565808403.jpg",
"https://open.spotify.com/artist/2uFUBdaVGtyMqckSeCl0Qj?si=dXzDPq5aRwOzF8EUMHYsiA"),
("Billy",
"Gibbons",
"Stati Uniti",
 "Gibbons venne al mondo il 16 dicembre 1949,come William Frederick Gibbons. È nato a Houston, in Texas, in un quartiere chiamato Tanglewood. La testa del rock ha avuto le sue influenze musicali da suo padre che era anche un musicista.
Il regalo di compleanno più emozionante di Gibbons era una chitarra elettrica e un amplificatore Fender Champ per accompagnarlo. Questi gli sono stati donati per il suo tredicesimo compleanno.
Per la sua educazione, Gibbons andò a Hollywood, in California. Qui ha studiato alla scuola d'arte della Warner Brothers. Fu durante il suo periodo qui che ha lavorato con diverse band come I cocchieri e Billy G e le Blueflames. All'età di 18 anni, Gibbons ha messo insieme la sua prima band attentamente insegnata che ha nominato I marciapiedi mobili. Il concetto e l'obiettivo del gruppo musicale sono stati ispirati dall'amico musicista di Billy, Roky Erikson e dal suo gruppo rock, Gli elevatori del 13 ° piano. I marciapiedi mobili aveva altri tre membri, il bassista Don Summers, il batterista Dan Mitchell e il tastierista Tom Moore.
Il suo gruppo rock ha iniziato a fare musica, tra cui il loro singolo di grande successo 99th Floor. Durante questo periodo incontrò anche la famosa rock star Jimi Hendrix e il duo divenne rapidamente il migliore amico. Questa amicizia ha respinto alcuni accordi commerciali. Gibbon di Il marciapiede mobile memorabilmente aperto per L'esperienza di Jimi Hendrix quattro volte nella loro carriera. Hanno anche pubblicato un album completo Veloce nel 1968.
Alla fine dell'anno successivo, Gibbons decise che era tempo di passare I marciapiedi mobili. Ha messo insieme la band ZZ Top con Dusty Hill e Frank Beard, entrambi strappati alla band American Blues. La somiglianza nei loro stili musicali l'ha fattafacile che il trio si leghi musicalmente e a livello personale. Nel 1971, sotto l'egida della London Records, il gruppo pubblicò il suo progetto di debutto intitolato Primo album di ZZ Top.",
 "https://img.freepik.com/free-photo/closeup-black-electric-guitar-dark-background_169016-20246.jpg?w=740&t=st=1678726216~exp=1678726816~hmac=bbefd2ffba7dd79c1107a5e7845d85d6b4e28b49e25bfd9ad705952f829b869d",
"https://nationaltoday.com/wp-content/uploads/2022/11/20-Billy-Gibbons-640x514.jpg",
"https://open.spotify.com/artist/69Iibc3uQ7x2vDeZxTwKCw?si=kP7IfV-LSrqXmSjY4cFU4A"),
("Tony",
"Iommi",
"Regno Unito",
"Anthony Frank Iommi nasce il 19 febbraio del 1948 a Birmingham (Inghilterra), dove - mentre lavora come riparatore di macchine da scrivere - impara a suonare la chitarra jazz/blues. Inizia a suonare in un gruppo, il cui nome da Polka Tulk diventa successivamente Earth per tramutarsi nel 1969 in Black Sabbath. Accompagnato da Ozzy Osbourne alla voce, da Terry “Geezer” Butler al basso e Bill Ward alla batteria, Iommi sviluppa il suo inconfondibile stile alla chitarra nonostante la pesante menomazione alla mano destra causatagli da un incidente sul lavoro. I dissidi e le continue scaramucce con Ozzy Osbourne contribuiscono all’allontanamento del cantante dai Black Sabbath, che lo sostituiscono nel 1982 con Ronnie James Dio. Nello stesso anno, quando anche Dio lascia la band, i Black Sabbath vivono un pericoloso momento di instabilità, ma è lo stesso Iommi che riesce a tenere unito il gruppo. Nel 1986 esce SEVENTH STAR e Iommi pone il suo nome accanto a quello dei Black Sabbath, quasi a voler sottolineare che il disco è fondamentalmente un parto della sua creatività. Alla fine degli anni ’90 avviene la riappacificazione tra Iommi e Ozzy Osbourne e dopo un lungo tour mondiale, i Black Sabbath si sciolgono definitivamente nel dicembre del ’99. L’anno successivo esce il suo primo disco solista, IOMMI, seguito da THE 1996 DEP SESSIONS (2004), album che – come dice già il titolo – viene registrato nel 1996, ma che ufficialmente non ha mai avuto prima una distribuzione. L’anno successivo è la volta di FUSED, realizzato in collaborazione con Glenn Hughes. Nel 2006 Iommi partecipa – assieme a Gezzer Butler e Ronnie James Dio – al progetto Heave and Hell, che porta il gruppo in tour con Megadeth e Down e da cui viene prodotto un disco, THE DEVIL YOU KNOW, uscito nell’aprile 2009.
A novembre 2008, Iommi viene incluso nella Birmingham Walk of Stars",
 "https://images.pexels.com/photos/164861/pexels-photo-164861.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
"https://www.rollingstone.it/wp-content/uploads/2022/11/tony-Iommi-1980.jpg",
"https://open.spotify.com/artist/7iA7uWUkWLpapsaaqmzRQV?si=BopGq0v1SauCUy-LJ2QoRA"),
("Nail",
"Young",
"Canada", 
"Neil Percival Young nasce il 12 novembre del 1945 a Toronto (Canada), figlio di un giornalista sportivo. Cresciuto a Omemee, a 130 chilometri dalla sua città natale, all'età di sei anni si vede diagnosticare il diabete e si ammala di poliomielite. Per colpa della malattia la parte sinistra del suo corpo risulta indebolita. A dodici anni Neil, in seguito al divorzio dei genitori, va a vivere in Manitoba, a Winnipeg, con la madre.
Nel periodo dell'adolescenza forma alcune band di garage rock e nel 1965 intraprende la carriera di musicista professionista con gli Squires, prima di dare vita ai Mynah Birds con Rick James. Successivamente Neil Young si trasferisce a Los Angeles con il bassista Bruce Palmer (anche perché James viene arrestato per renitenza alle armi): in questo periodo vive negli USA in modo illegale. Solo nel 1970 riceve la Green Card.
Nel frattempo si esibisce con i Buffalo Springfield, che diventano uno dei gruppi più importanti della California: al suo fianco ci sono, oltre a Palmer, Dewey Martin, Richie Furay e Stephen Stills. Tuttavia i rapporti tra i componenti del gruppo si deteriorano ben presto, sia per i problemi di droga di Palmer che per i diverbi con il management. Così nel 1968 la band si scioglie.
Young, a quel punto, sottoscrive con la Reprise Records un contratto da solista e all'inizio del 1969 dà alle stampe il disco "'Neil Young'". Dopodiché recluta Billy Talbot, Danny Whitten e Ralph Molina per creare i Crazy Horse, con i quali registra "'Everybody knows this is nowhere'" (maggio 1969), album che contiene, tra gli altri, "'Down by the river'", "'Cowgirl in the sand'" e "'Cinnamon girl'". Più tardi Young ritrova l'amico Stills aggiungendosi al trio "'Crosby, Stills & Nash'", band che aveva già pubblicato un album. Il quartetto, rinominato "'Crosby, Stills, Nash & Young'", debutta a Chicago il 16 agosto 1969, e successivamente si esibisce al celeberrimo Festival di Woodstock, durante il quale però Young rifiuta di essere filmato.",
 "https://img.freepik.com/free-photo/white-electric-guitar-dark-background_23-2147781788.jpg?w=360&t=st=1678726607~exp=1678727207~hmac=d633c6920ee4cf4d130390bb5cb4187689af205d379bc37eeef8bf2ba5d94ad1",
"https://guitar.com/wp-content/uploads/2021/10/neil-young@2000x1500.jpg",
"https://open.spotify.com/artist/6v8FB84lnmJs434UJf2Mrm?si=YqL15_BwSceC-knOu6ov_A"),
("Calum",
"Graham",
"Canada",
"Calum Graham is a Canadian fingerstyle guitarist and singer-songwriter. He has classical guitar training, but uses a percussive technique. He has released four albums. When he was 22 he was listed by Acoustic Guitar magazine as one of their 30 "'great guitarists under 30'"
In 2009 Graham won the Calgary Stampede Talent Search, and also the ensuing national-level talent contest.
He came second in the fingerstyle guitar competition at the 2009 Canadian Guitar Festival, and won it in 2010.
In 2011 he won the Canada's Walk of Fame "'A Song For Canada'" song contest. The prize included C$25,000 in cash, and time in a recording studio.",
"https://img.freepik.com/free-photo/closeup-cutaway-acoustic-guitar-black-background_1150-6343.jpg?w=1060&t=st=1678727010~exp=1678727610~hmac=bbf6607a48a7dc5ad2d1ae1cae76c6c8eb42af88a0916f8484195c79d0670d92",
"https://www.adticket.de/images/event/440/c/calum_graham_2022.jpg",
"https://open.spotify.com/artist/6VUCcZ6HiQQ39DhxV4bSeA?si=7f4PPV-9Sh2Si3BSAdtKOQ"),
("Giovanni",
"Allevi",
"Italia", 
"Giovanni Allevi nasce ad Ascoli Piceno il 9 aprile 1969. Si diploma al conservatorio Francesco Morlacchi di Perugia nel 1990 con il massimo dei voti in pianoforte; nel 1998 si laurea in Filosofia con lode con la tesi "'Il vuoto nella Fisica contemporanea'". Nel 2001 consegue il diploma in composizione al Conservatorio Giuseppe Verdi di Milano e frequenta l'"'Accademia Internazionale di Alto Perfezionamento'" di Arezzo, sotto la guida del maestro Carlo Alberto Neri.
Giovanni Allevi presta nel 1991 il servizio militare nella Banda Nazionale dell'Esercito Italiano: il suo talento pianistico non passa inosservato tant'è che il maestro della banda decide così di includere il pianoforte solista nel suo repertorio. In veste di pianista solista della Banda, Giovanni effettua la "'Rapsodia in blu'" di George Gershwin ed il "'Concerto di Varsavia'" di Richard Addinsell, portandolo in tour in molti teatri italiani. Congedatosi dal servizio militare, presenta in concerto un repertorio che annovera unicamente le proprie composizioni per pianoforte; contemporaneamente frequenta i corsi di "'Bio-musica e musicoterapia'" del prof. Mario Corradini, in cui questi analizza l'argomento del potere della musica di rendere liberi, di rievocare ricordi, immagini ed emozioni.
Nel 1996 Allevi compone la musica per la tragedia "'Le Troiane'" di Euripide che è rappresentata al Festival Internazionale del Dramma Antico di Siracusa; con queste vince il premio speciale per le migliori musiche di scena. Nel 1997 vince le selezioni internazionali per giovani concertisti al "'Teatro San Filippo'" di Torino.
Al fine di dedicarsi alla musica da professionista e per cercare un "'mercato'" che gli conceda più possibilità, Giovanni Allevi matura l'idea di trasferirsi a Milano, in seguito anche ai consigli dell'amico e compaesano Saturnino Celani (bassista dalla professionalità internazionale). A questo punto raccogliere in un cd la propria produzione pianistica ed il suo lavoro piace particolarmente a Lorenzo Cherubini che lo edita con la sua etichetta "'Soleluna'" assieme alla "'Universal Italia'". Con essa pubblica i suoi primi due album per pianoforte solo "'13 dita'" (1997 - prodotto in studio da Saturnino) e "'Composizioni'" (2003) con i quali Allevi mostra la freschezza della sua invenzione musicale e l'attualità della sua produzione compositiva, riscuotendo ampi consensi di critica. La collaborazione con Saturnino e Jovanotti gli apre il mercato con il pubblico delle grandi platee dei concerti pop. Allevi apre così, solamente assieme al suo pianoforte, i concerti di Jovanotti durante il tour "'L Albero'".
Nel 1998 sempre con la produzione di Saturnino realizza la colonna sonora del cortometraggio "'Venceremos'" presentato al Sundance Film Festival negli Stati Uniti. Nel 1999 la musicista giapponese Nanae Mimura, solista di "'marimba'", propone alcuni brani di "'13 dita'" trascritti per il suo strumento al Teatro di Tokyo ed in un concerto alla Carnegie Hall di New York.
L album "'13 dita'" riscuote un notevole successo di critica e Jovanotti invita nuovamente Giovanni Allevi a partecipare in qualità di pianista al tour "'Il quinto mondo - Jovanotti 2002'", per il quale cura anche gli arrangiamenti della band composta da sedici musicisti. All'interno dello spettacolo, Giovanni regala al pubblico, in anteprima, in una sua performance solistica, "'Piano Karate'", uno dei brani contenuti nel nuovo album.
Finita l esperienza del tour Allevi si concentra su un nuovo progetto musicale completamente suo: un opera live dal titolo "'La favola che vuoi'", che lo porta nel 2003 alla pubblicazione del suo secondo album per pianoforte solo, dal titolo "'Composizioni'" (Ed. Soleluna/Edel).
Con l'attività di pianista Giovanni Allevi si conferma musicista eclettico, esibendosi in prestigiose rassegne concertistiche di musica classica, in importanti teatri italiani, e nei festival di musica rock e jazz.
Dal giugno 2004 inizia un tour internazionale dal palco dell'HKAPA Concert Hall di Hong Kong. È il segno di una crescita artistica inarrestabile al di là delle ristrette categorie musicali, che il 6 marzo 2005 lo porta ad esibirsi sul palco del tempio mondiale del Jazz: il "'Blue Note'" di New York, dove registra due strepitosi sold-out.
A conferma dell'impegno intellettuale e della valenza culturale della sua figura artistica, viene invitato a tenere un seminario su "'La Musica dei nostri giorni'" all'Università di Pedagogia di Stoccarda, e sul rapporto tra Musica e Filosofia alla School of Philosophy di New York.
Nel 2004 insegna Educazione Musicale in una scuola media statale di Milano. L'affermazione in ambito internazionale come compositore arriva dal Baltimora Opera House (USA), per la rielaborazione dei recitativi della "'Carmen'" di Bizet, una delle opere liriche più amate e conosciute dal pubblico di tutto il mondo.
Ad aprile del 2005 Giovanni Allevi si esibisce al Teatro Politeama di Palermo, in una "'première'" della sua prima opera per pianoforte e orchestra "'Foglie di Beslan'", con i 92 elementi dell Orchestra Sinfonica Siciliana che gli ha commissionato la composizione. Sempre nel 2005 riceve due importanti riconoscimenti: a Vienna è insignito dell'onoreficenza di "'Bosendorfer Artist'", per la "'valenza internazionale della sua espressione artistica'", e dalla sua terra di origine, il Premio "'Recanati Forever per la Musica'" per l'eccellenza e la magia con cui accarezza i tasti del suo pianoforte.
A maggio 2005 pubblica il suo terzo album per pianoforte solo: "'No concept'" (Bollettino/BMG Ricordi) presentato anche in Cina e a New York. Il brano "'Come sei veramente'" tratto da questo album è scelto dal grande regista statunitense Spike Lee, come colonna sonora per un nuovo spot internazionale della BMW. "'No concept'", da settembre 2005 è pubblicato anche in Germania e Corea, poi anche in altri paesi.
Il 18 settembre 2006 all'Arena Flegrea di Napoli riceve il "'Premio Carosone'" come miglior pianista dell'anno "'per il senso melodico del suo pianismo, [...] per il suo muoversi oltre ogni barriera di genere, al di fuori di qualsiasi categoria e definizione'".
Molti degli addetti ai lavori infatti sostengono che il suo successo sia un prodotto di un abile operazione di marketing e non di una reale capacità di innovazione musicale che lo stesso Allevi rivendica. A questo seguono non poche critiche negative sui quotidiani ad opera di musicisti e giornalisti.
Di sicuro Allevi è tra i pianisti italiani più conosciuti al mondo, per estro creativo, bravura e tecnica. Al di là che la sua produzione musicale possa piacere o essere compresa, è cristallina la capacità di questo genio della tastiera di rielaborare la tradizione classica europea aprendola alle nuove tendenze pop e contemporanee, trovandosi di fatto a suo agio sia nei teatri che di fronte alle platee dei concerti rock.",
 "https://img.freepik.com/free-photo/piano-wooden-background-closeup-concept-musical-instruments_169016-4829.jpg?w=740&t=st=1678726852~exp=1678727452~hmac=3a6ed053d3ca2e8a2af2c886bad84e8c8510160c97d1de815c2234d11772e6d9",
"https://www.costasmeralda.it/wp-content/uploads/2021/08/Giovanni-Allevi.jpg",
"https://open.spotify.com/artist/4cU35zPQE7ZwPk72IM4wHv?si=zYDx2-ccSgGyLlmmoL25Zw"),
("Lee",
"Ru-ma",
"Sud Corea", 
"Yiruma (Seul, 15 Febbraio 1978) è un pianista sudcoreano, sposato con Miss Corea Son Hye-im.
Yiruma è conosciuto in tutto il mondo ed i suoi album sono venduti in tutta l'Asia, in Europa e in parte degli Stati Uniti. Alcuni dei suoi pezzi più famosi sono Kiss the rain, Maybe e River flows in you del suo album First Love.
In molti forum e siti di fan, Kiss the rain e Riwer flows in you venivano suggerite come musiche ideali per il film Twilight di Catherine Hardwicke, rispettivamente come la ninna nanna di Bella (Kiss the Rain) e la canzone preferita da Esme (River flows in you). In realtà, le due canzoni non compaiono nel film: infatti tutte le musiche sono state scritte dal compositore Carter Burwell, compresa quella suonata da Edward, Bella's Lullaby.
Benché precedentemente avesse due cittadinanze, inglese e Sud Coreana, nel luglio 2006 rinunciò a quella inglese per entrare nella marina militare Sud Coreana, dato che doveva iniziare il servizio militare obbligatorio per tutti gli uomini Sud Coreani.
Yiruma iniziò a studiare pianoforte all'età di 5 anni. Nel 1998 si trasferì in Inghilterra, e nel dicembre 1996 partecipò all'album The Musicians of Purcell dei Decca Records. Si laureò alla Purcell Of Specialist Music School a Londra nel luglio 1997, ed in seguito al Kings College nel giugno del 2000.",
 "https://img.freepik.com/free-photo/closeup-white-piano-keys-musical-background_169016-19730.jpg?w=1060&t=st=1678726978~exp=1678727578~hmac=a88d103e488a2e22083ac390f0e2922f1b94168f0fc16d4689766d760dd9ea6c",
"https://charts-static.billboard.com/img/2010/01/yiruma-rvh-344x344.jpg",
"https://open.spotify.com/artist/0fauHpmSHwodVYIjTqOGHz?si=IFBL7ziWRruCGFRCxKxClQ"),
("Louis",
"Armstrong",
"Stati Uniti", 
"Nei primi anni della sua vita non sembrava certo che Louis Daniel Armstrong fosse nato sotto una buona stella.
Messo al mondo da una domestica e da un tizio che abbandonò entrambi quando lui era piccolissimo, la prima luce che vide fu quella rossa dei bordelli del quartiere di Storyville a New Orleans, dove crebbe in fretta, nella miseria più nera.
A proposito della sua nascita c’è un retroscena che resta ancora un piccolo giallo: Armstrong dichiarò sempre di essere nato il 4 luglio del 1900, ma, in realtà, studi recenti, sovvenzionati dalla stessa New Orleans, hanno dimostrato che la sua vera data di nascita era il 4 agosto del 1901 e che probabilmente aveva voluto “invecchiarsi” di un anno e un mese, per risolvere delle questioni legate ai suoi esordi giovanili a Chicago e New York, dove non voleva sembrare più giovane di quello che era.
Il giorno di san Silvestro del 1912, o forse era il 1913, varcò le porte del riformatorio perché trovato con un revolver in mano, con cui alcuni dicono stesse festeggiando a modo suo il Capodanno, ma c’è chi dice che avesse preso parte ad uno scontro tra gang rivali. Fatto sta che in riformatorio ci passò un anno e mezzo, ma fece qui l’incontro che gli cambiò la vita. Una guardia gli regalò una vecchia cornetta ammaccata e da lì iniziò ad essere chiamato Dippermouth (bocca a mestolo). Entrò nella banda dell’istituto, la Waim’s Home band dove il suo maestro Peter Davis gli insegnò i rudimenti di questa sorta di “succedaneo” della tromba. La banda dell’istituto era molto amata dalla gente di New Orleans. Girò le strade suonando pezzi in voga all’epoca come “When He Saints Go Marchin’in” che, parecchi anni dopo, diventerà uno dei cavalli di battaglia di Louis.
All’uscita dal riformatorio Louis iniziò a suonare nelle sfilate dei giorni di festa e ai funerali: nella sua biografia lui stesso racconta l’emozione di vedere puttane e biscazzieri affacciarsi per vedere passare i suonatori. Solo nel 1918, incentivato dal lavoro sui “riverboats” (i battelli che navigavano sul Mississippi), Armstrong imparò a leggere le partiture, diventando un musicista completo.
Un’ usanza delle orchestre di New Orleans era di esibirsi per le strade a bordo di camion, incrociarsi e iniziare sfide all’ultima nota.
Un giorno Armstrong incrociò per strada il camion di Kid Ory, allora uno dei trombettisti più famosi, il quale, vedendolo con una tromba tra le mani gli chiese a chi la stesse portando. “A nessuno. ? mia”, rispose Louis. Loro non gli credettero, lui cominciò a suonare e fu imbarcato sul camion. La sua fama cominciò a crescere. Nell'agosto del 1922 King Oliver, un altro famoso musicista residente a Chicago, gli inviò un telegramma chiedendogli di unirsi alla sua Creole Jazz Band, nella quale Louis ebbe la possibilità di far spiccare l'estremo virtuosismo che ormai aveva acquistato con il suo strumento; è infatti opinione comune di appassionati e storici affermare che Louis avesse inventiva, fantasia ritmica e melodica, unite ad un impressionante volume sonoro e ad un inconfondibile timbro.
Nel 1923 fece le sue prime registrazioni come membro della King Oliver’s Creole Jazz Band.
Il 1924 fu un anno importante per Armstrong: diventò “Satchmo”(bocca a sacco), lasciò l’orchestra di Oliver e si trasferì a New York per entrare nella Fletcher Henderson Orchestra una delle migliori in circolazione, fatta dai più virtuosi solisti in circolazione.
In questo periodo registra con grandi protagoniste del blues come Sippie Wallace e Bessie Smith.
Nel 1925 decise di tornare a Chicago e intraprendere la carriera da solista. Fondò il gruppo di cui era il leader, Louis Armstrong and His Hot Five, che trasformano il jazz in una delle più alte espressioni musicali. Seguirono poi incisioni considerate fondamentali nella storia del jazz come quella nel 1928 di “West End Blues” .
Tra il 1930 e il 1935 fece tournée in Europa, arrivò a trecento concerti all’anno e di cui tutti successi clamorosi. Fu conteso dalle migliori orchestre americane, suonò nei locali più famosi, collaborò con i grandi della scena internazionale come Jimmie Rodgers con cui registrò nel 1930 “Blue Yodel No.9”.
Partecipò a più di trenta film interpretando per lo più se stesso: il solista famoso.
Nel 1931 registrò “When It’s Sleepytime Down South”, che diventò il suo cavallo di battaglia e nel 1936 uscì “Swing That Music”, che lasciò il pubblico senza fiato.
Nel 1947 gli venne organizzato un concerto spettacolare alla Carnegie Hall: un trionfo.
Fondò il complesso dei “Louis Armstrong and the All Stars”, che debuttò a Hollywood e tenne concerti dall'Australia all'Europa e al Giappone, dove riceveva sempre accoglienze da re.
Partecipò nel 1948 al Jazz Festival di Nizza, il primo festival jazz internazionale.
Tra touneé mondiali, pubblicazioni di autobiografie e comparse in film e trasmissioni televisive, nel 1954 Louis registrò Satchmo: A Musical Autobiography e Louis Armstrong Plays W.C. Handy, seguiti nel 1955 da Satch Plays Fats.
Nel 1959 venne ospitato al Festival dei Due Mondi di Spoleto e fu un trionfo.
In questi anni fu accusato di essere un conformista, un negro alla zio Tom, incurante della causa dei suoi fratelli. Ma quando vide alla televisione gli scontri per l'integrazione razziale e un bianco che sputava in faccia a una studentessa negra, mandò all'inferno il governo americano e rifiutò un tour in Russia organizzato dal Dipartimento di Stato.
Nel 1964 “Hello Dolly” riscuote un successo enorme, salendo in cima alle classifiche.
Nel 1967 registra l’intramontabile “What a Wonderful World”, uno dei pezzi che più rappresentano il cuore e l’anima di Armstrong.
Ricco e famoso, continuò ad esibirsi e nel 1968 approdò come "'concorrente'" a Sanremo con "'Mi va di cantare'", lo stesso anno di Disney Songs the Satchmo Way.
Nel 1970 a Los Angeles partecipò alla grande festa organizzata per il suo 70° compleanno (allora è nato nel 1900?).
Un anno dopo, il 6 luglio del 1971muore nella sua casa di New York. L’epitaffio migliore gli è stato dedicato dal poeta Evtusenko, che raccomandò all'arcangelo Gabriele di “…dare ad Armstrong una tromba, perché rallegri gli angeli e i peccatori all'inferno abbiano alleviate le loro pene”.",
 "https://img.freepik.com/premium-photo/part-old-clarinet-body-with-silver-mechanisms-wood-black-background-free-space-text_37195-549.jpg?size=626&ext=jpg&uid=R94944374&semt=sph",
"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/louis-armstrong-1651141819.png",
"https://open.spotify.com/artist/19eLuQmk9aCobbVDHc6eek?si=GB6BIvc5QOCkD9lEwDkLAQ"),
("Tash",
"Sultana",
"Australia", 
"Natasha “Tash” Sultana nasce a Melbourne il 15 giugno 1995. Il primo strumento inizia a suonarlo all’età di soli 3 anni, grazie al padre che le regala una piccola chitarra. Da questo momento in poi non smetterà mai di sperimentare nuovi strumenti e nuovi suoni. Adesso, a soli 24 anni è in grado di suonare perfettamente dieci strumenti: voce, chitarra, basso, pianoforte, tastiera, tromba, batteria, flauto di Pan, mandolino, sassofono e percussioni.
Facciamo un passo indietro. Prima di arrivare a questo punto Tash Sultana ha dovuto affrontare delle prove durissime, prove senza le quali probabilmente non sarebbe mai riuscita ad arrivare dov’è. Sicuramente la dedizione e la passione verso la musica sono innate ma un episodio in particolare l’ha “costretta” a dedicare anima e corpo alla musica, riuscendo a farsi salvare da quest’ultima.
All’età di 17 anni l’australiana Tash Sultana aveva provato già tutte le droghe possibili e probabilmente avrebbe continuato a farlo se non fosse arrivata al punto di dover affrontare una grave psicosi provocata dall’abuso di droghe. La sua ultima esperienza con i funghetti allucinogeni fu così terribile che non cessò dopo alcune ore, come spesso accade, ma durò nove lunghi mesi, periodo in cui la musicista faceva fatica persino a separare la fantasia dalla realtà.
È proprio il caso di dirlo: Tash Sultana è stata salvata dalla musica. Oltre alla terapia standard da seguire per curare questo tipo di psicosi, l’australiana si è buttata a capofitto nella musica imparando da zero e perfezionando sempre più le sue capacità. 
Il successo arriva quando inizia a caricare dei video sul suo canale Youtube. Jungle è uno dei brani più famosi della polistrumentista australiana.",
 "https://img.freepik.com/free-photo/closeup-part-drum-kit-blurred-background_169016-20617.jpg?w=1060&t=st=1678727320~exp=1678727920~hmac=2816bcfdf878665502a9a4a699153956f9a69ef11423d949c6823637a3ff6662",
"https://www.rollingstone.com/wp-content/uploads/2018/06/tashsultana-1920x1080-dbffc095-d65e-47c9-beb8-62f2a49a6d70.jpg",
"https://open.spotify.com/artist/6zVFRTB0Y1whWyH7ZNmywf?si=KHBvNjrXSHSmKE2yDM5law"),
("Jimmy",
"Page",
"Regno Unito", "James Patrick Page, detto Jimmy, nasce il 9 gennaio del 1944 a Londra, nel sobborgo di Heston. Sin dall'adolescenza si appassiona alla chitarra, divenendo presto allievo di Big Jim Sullivan, session man che già era stato l'insegnante di Ritchie Blackmore, membro dei Deep Purple. A quattordici anni prende parte a "'Search for stars'", programma televisivo in cerca di nuovi talenti, mentre due anni più tardi decide di lasciare la scuola per intraprendere definitivamente la carriera musicale.
Dopo aver collaborato con il cantante Red E. Lewis e il poeta Royston Ellis, segue Neil Christian e la band dei The Crusaders a Parigi, prima di suonare per il suo singolo intitolato "'The road to love'". Una sera, Jimmy viene notato da John Gibb, componente dei The Silhouettes, che gli chiede di collaborare con lui per registrare alcuni brani per la Emi; la stessa offerta gli viene avanzata dalla Decca Records, che gli promette un lavoro come turnista in studio. Dopo aver suonato, tra l altro, per Mickey Finn and the Blue Men, registra per Marianne Faithfull, i Rolling Stones, The Nashville Teens, Brenda Lee, Dave Berry e Van Morrison & Them. Accolto positivamente dalle band con cui lavora, partecipa alla registrazione di "'I can t explain'", primo singolo degli Who, anche se poi nel missaggio finale le parti suonate da lui vengono tagliate.
Nel 1965, quindi, Page viene assunto dal manager dei Rolling Stones Andrew Loog Oldham, come produttore della casa Immediate records, appena nata: egli, così, ha la possibilità di produrre brani per Eric Clapton, Chris Farlowe, Nico e John Mayall. Nel frattempo, incide "'The bells of Rhumney'", cover della ballata omonima di Pete Seeger. Dopo aver rifiutato il posto di Eric Clapton negli Yardbirds (al suo posto raccomanda Jeff Beck, suo amico), partecipa alla registrazione di "'Beck s Bolero'" con Keith Moon: di lì a poco, torna sui suoi passi e decide di accettare un ruolo negli Yardbirds, anche se come bassista. Le cose, tuttavia, non vanno benissimo, a causa dell'abbandono di Jim McCarty e di Keith Relf e dei dissapori con Jeff Black: Jimmy, in ogni caso, vuole proseguire la vita del gruppo.
Nascono così i Led Zeppelin, nome suggerito da una frase di Keith Moon, che aveva detto, dopo gli abbandoni degli altri membri, che la band sarebbe caduta come un dirigibile di piombo ("'A lead zeppelin'"). Con i Led Zeppelin, Jimmy Page ottiene un successo stratosferico, nel doppio ruolo di produttore e chitarrista: egli diventa uno degli esponenti più importanti del sound rock del tempo, grazie all unione della Gibson Les Paul con l amplificatore Marshall (anche se per il primo album viene utilizzata una Fender Telecaster).
L'impiego di chitarre acustiche, slide e distorsioni rendono il gruppo il modello di diverse rock band degli anni e dei decenni seguenti. Durante la sua militanza nei Led Zeppelin, Jimmy si fa apprezzare, tra l'altro, per la tecnica tapping, come evidenziato dall'assolo del brano "'Heartbreaker'". Egli, inoltre, impiega un archetto di violino al fine di pizzicare le corde della chitarra.
I Led Zeppelin si sciolgono dopo la morte di John Bonham, batterista della band, nel 1980. Page torna alla grande in un'esibizione del 1983 tenuta alla Royal Albert Hall: un concerto benefico cui partecipano anche Jeff Beck e Eric Clapton. L'anno successivo, egli registra un disco con Robert Plant usando il nome di The Honeydrippers: un progetto che anticipa altre collaborazioni con Paul Rodgers, Graham Nash e David Coverdale, oltre a un tour realizzato con i Black Crowes.
Dopo aver realizzato la colonna sonora dei film "'Il giustiziere della notte II'" e "'Il giustiziere della notte III'", Page torna a suonare con i Led Zeppelin nel 1985 in occasione del Live Aid, con Phil Collins al posto di Bonham: si tratta, però, di un'esibizione sottotono, come dimostra il rifiuto di immortalarla nel Dvd realizzato in occasione del ventesimo anniversario dell'evento.
Nel 1994, poi, Jimmy suona a Mtv Unplugged con Plant, in uno speciale di novanta minuti che raccoglie un enorme successo, al punto da dare origine a un album chiamato "'No quarter'". Segue un tour nell'anno successivo, che anticipa il nuovo disco "'Walking into Clarksdale'". Nel frattempo il musicista inglese si dedica anche ad attività di beneficenza, soprattutto in favore dell'Action for Brazil's Children Trust, organizzazione fondata nel 1998 dalla moglie Jimena Gomez-Paratcha, che mette a disposizione istruzione, cibo e supporto medico per i bambini brasiliani che vivono in povertà. Nel 2005, Page viene insignito, proprio per la sua attività benefica, dell Order of the British Empire, mentre poco dopo, per lo stesso motivo, gli viene assegnata la cittadinanza onoraria di Rio de Janeiro.
Dopo aver preso parte alla cerimonia di chiusura delle Olimpiadi di Pechino del 2008, suonando la canzone "'Whole lotta love'" interpretata da Leona Lewis, partecipa a "'It might get loud'", film-documentario dedicato alla chitarra, insieme a Jack White dei Dead Weather e a The Edge degli U2. Nel frattempo, non rinuncia all'intenzione di tornare a suonare con i Led Zeppelin, anche se John Paul Jones e Robert Plant non sembrano essere dello stesso avviso.
Sono numerosi i chitarristi che nel corso degli anni si sono ispirati alla figura di Jimmy Page: tra gli altri, si segnalano Richie Sambora dei Bon Jovi, Joe Perry degli Aerosmith, Brian May dei Queen, Angus Young degli AC/DC, Slash dei Guns n Roses, James Hetfield dei Metallica, e in Italia Maurizio Solieri (del gruppo di Vasco Rossi) e Alex Britti.
Nel 2003, Page, intervistato da "'Guitar World'", ha ammesso di aver consumato droghe pesanti nel corso della sua carriera, soprattutto negli anni Settanta: l'uso di eroina è iniziato nel 1975, ed è proseguito durante le registrazioni di "'Presence'". La droga ha rappresentato un problema evidente nella vita del chitarrista: il tour americano del 1977, per esempio, ne ha risentito pesantemente. Il ricorso all eroina si è fatto sentire sia dal punto di vista fisico (Page è calato di peso in quegli anni), sia dal punto di vista psicologico, visto che essa ha causato diversi litigi nella band, soprattutto con Robert Plant, cui non piacevano le performance di Jimmy.
Il chitarrista britannico è padre di Scarlet (avuta da Charlot Martin), attualmente celebre fotografa, James Patrick III (avuto da Patricia Ecker) e Jana, Zofia e Ashen Josan (avuti dalla moglie attuale, Jimena Gomez-Paratcha).",
 "https://images.pexels.com/photos/3807656/pexels-photo-3807656.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
"https://www.superprof.it/blog/wp-content/uploads/2017/07/chitarra-jimmy-page.jpg.webp",
"https://open.spotify.com/artist/55bGuHb50r5c0PeqqMeNBV?si=TndHoqDVQ6ySXDCDGtxUcA"),
("Chuck", 
"Berry",
"Stati Uniti",  
"Charles Edward Anderson Berry, o più semplicemente Chuck Berry, nasce a Saint Louis, nello stato del Missouri, in Usa, il 18 ottobre del 1926. Cantante e compositore, tra i primi chitarristi rock di sempre, si contende - e probabilmente sempre si contenderà - con Elvis Presley, il primato per aver inventato o, quanto meno, portato al successo, il genere più famoso del Novecento: il rock and roll.
Di sicuro Chuck Berry è stato il primo ad aver utilizzato la scala pentatonica negli assolo di rock, la cosiddetta "'double-stop'", portando il suo strumento, la chitarra, a gareggiare quando non proprio a primeggiare sulla voce, fino agli anni 50 considerata la cosa principale di qualsiasi band e in qualsiasi genere musicale. Secondo la celebre rivista "'Rolling Stones'" è al quinto posto nella speciale classifica dei cento migliori chitarristi della storia del rock.
Gli anni giovanili di Chuck sono quelli consueti, soprattutto per quei ragazzi di colore che, nell'America degli anni 40, devono lottare contro i pregiudizi razziali e, soprattutto, contro le prepotenze della classe dirigente bianca. È un ragazzo turbolento, con una forte tendenza a delinquere. Gli anni che passa in riformatorio, durante l'adolescenza, non sono di certo pochi.
Quarto figlio di una famiglia di sei figli, si fa le ossa nel quartiere "'The Ville'". Suo padre è un diacono della chiesa battista e si dà da fare come imprenditore, dando tuttavia alla famiglia numerosa una certa agiatezza economica, soprattutto a confronto con molte altre famiglie di colore degli Stati Uniti, in quegli anni in grande difficoltà.
Il piccolo Chuck si innamora ben presto del blues e della chitarra, esibendosi davanti ad un pubblico sin nel lontano 1941, quando è poco più che un teenager, presso la Sumner High School. Da questo momento però, per tre anni, il giovane musicista frequenta le cosiddette cattive compagnie, tanto che nel 1944, ancora studente, viene arrestato e incarcerato per rapina a mano armata, insieme con la sua banda. La delusione per i famigliari è forte e il giovane viene spedito ad Algoa, nel riformatorio vicino Jefferson City, nel Missouri. Durante la detenzione conosce altri musicisti, forma con loro un quartetto vocale e si allena come pugile. In breve intuisce che la musica può essere la sua unica maniera per emergere e stare lontano da certe situazioni criminose.
All'età di ventuno anni, una volta fuori di prigione, Chuck Berry sposa la sua fidanzata Themetta "'Toddy'" Suggs, esattamente il 28 ottobre del 1948. Due anni dopo arriva la prima figlia, Darlin Ingrid Berry, nata il 3 ottobre del 1950.
In questo periodo, pur non abbandonando mai la musica, il futuro chitarrista si dà da fare con diversi lavori, arrangiandosi a St. Louis come operaio, portinaio e altro. Nello stesso anno in cui nasce la figlia, la famiglia Berry riesce a comprare un piccolo appartamento in Whittier Street (verrà poi dichiarato edificio storico proprio per aver ospitato l'idolo rock in quegli anni).
Prima del 1955, anno fatidico per lui dal punto di vista musicale, Berry pensa alla musica come ad un suo secondo lavoro, suonando con varie formazioni, prediligendo il blues ma non disdegnando nemmeno il country, la musica dei bianchi. Nel 1953 conosce una certa notorietà al seguito del pianista Johnnie Johnson, dando inizio a una lunga collaborazione.
A dare una svolta alla sua carriera è il grande bluesman Muddy Waters, il quale fa il suo nome a Leonard Chess, della Chess Records di Chicago. Nel maggio del 1955 Berry si presenta con un lavoro fatto e finito, tutto blues, che però non interessa più di tanto il titolare dell'etichetta. Questi però, rimane sorpreso da una sorta di scherzo inciso da Berry e compagni, un riadattamento di un vecchio classico country & western di Bob Wills, intitolato "'Ida Red'", e trasformato in "'Ida May'". Il chitarrista e cantante viene convinto a incidere nuovamente il brano che, il 21 maggio 1955, diventa "'Maybellene'". Con lui ci sono il pianista Johnnie Johnson, Jerome Green alle maracas, il batterista Jasper Thomas e il bassista e cantante blues Willie Dixon. La canzone quell'anno vende un milione di copie e porta Chuck Berry e i suoi in vetta alle classifiche americane. Il brano in questione, secondo molti, segna forse il vero inizio del genere "'Rock and Roll'", frutto della commistione tra rythm and blues e country.
A dare una battuta d'arresto alla sua lanciatissima carriera di musicista è ancora una volta una vicenda giudiziaria, la quale incide non poco sull'immaginario comune. Nel 1959 l'autore della celebre e sempre amata "'Johnny B. Goode'", suonata dai più grandi di sempre e colonna sonora di film di successo, viene arrestato per avere avuto rapporti sessuali con una minorenne: una quattordicenne impiegata in uno dei suoi locali. La condanna inizialmente è di cinquemila dollari di multa e ben cinque anni di carcere. Tuttavia, due anni dopo, ricorso in appello nel 1961, Berry ottiene una riduzione della pena a tre anni di reclusione.
Di nuovo in libertà nel 1963, il musicista di colore fatica a rientrare nel giro che conta. In parte sono proprio le nuove band della cosiddetta "'British invasion'" a salvarlo, riportando in auge il suo nome e molti dei suoi migliori brani. Gruppi come i Rolling Stones, i Beatles, i Beach Boys gli tributano il dovuto, rielaborando i suoi migliori singoli.
John Lennon di lui ha modo di affermare: "'È uno dei più grandi di sempre. L ho già detto molte volte, ma è il primo vero poeta rock.'".
Fino al 1965 Chuck Berry vivacchia di rendita, pubblicando in totale altri otto singoli interessanti, ma non dello stesso livello dei precedenti. Entro il 1969 pubblica cinque dischi per la Mercury, compreso un live a Fillmore, ma senza ottenere molta attenzione dal pubblico e da parte degli addetti ai lavori. È ancora una volta la Chess Records a portargli fortuna. Nel 1972 per la sua vecchia casa incide una nuova versione dal vivo della sua vecchia canzone "'My Ding-a-Ling'". Il brano, sorprendendo lo stesso chitarrista, balza in testa alle classifiche.
Dopo quest ultimo momento di gloria, Berry continua ad esibirsi dal vivo fino al 1979, quando il giorno 1 giugno viene chiamato a suonare alla Casa Bianca, davanti al presidente Jimmy Carter. Nel frattempo pubblica altri due dischi, non particolarmente esaltanti: "'Chuck Berry'", del 1975, e "'Rock It'", del 1979.
Sempre nel 1979 l artista americano sconta altri quattro mesi di prigione, oltre a un cospicuo numero di ore nei servizi sociali, questa volta a causa di una condanna per evasione fiscale.
Dagli anni 80 in poi, nonostante tutte le vicissitudini che lo riguardano, Berry si rimette in sesto e si dedica con tutto se stesso ai concerti dal vivo, realizzandone un centinaio ogni anno e per tutto il decennio. Nel 1986 Taylor Hackford gira un documentario su di lui, dal titolo "'Hail! Hail! Rock and Roll'", e incentrato sul festival celebrativo fatto in suo onore, per il suo sessantesimo compleanno. Per l'occasione, a tributare Berry, ci sono i migliori di sempre: da Keith Richards a Eric Clapton, fino ad Etta James, Julian Lennon, Robert Cray e Linda Ronstadt.
Alla fine del 1990 l'artista fa parlare ancora di sé e per motivi non riguardanti la sua musica. Deve pagare circa un milione di dollari a 59 donne che lo accusano di aver installato una telecamera nei bagni di un suo famoso ristorante nel Missouri, con il fine di spiarle nei momenti meno opportuni. Durante la perquisizione che subisce, vengono trovati a casa sua oltre a dei video compromettenti, con immagini registrate dai bagni del suo locale, tra le quali comparirebbe anche una minorenne, anche sessanta grammi di marijuana. Berry patteggia e se la cava con due anni di libertà vigilata e circa cinquemila dollari di multa.
Dieci anni dopo, nel 2000, è il suo ex pianista Johnnie Johnson a citarlo in giudizio, con l'accusa di mancati crediti ricevuti per quanto riguarda canzoni come "'No particular place to go'", "'Sweet little sixteen'" e "'Roll over Beethoven'", delle quali sostiene di essere il coautore. Ma questa volta il chitarrista ha la meglio sul suo ex pianista.
Negli anni successivi e nonostante l'età, Chuck Berry continua le sue esibizioni a St. Louis senza rinunciare nemmeno ai tour europei, come quello cominciato nel 2008, il quale lo ha portato un po' ovunque e anche con buon successo di pubblico.
Rimane in attività fino alla fine della sua vita. La morte lo coglie all'età di 90 anni, il 18 marzo 2017, nella sua città natale.",
"https://img.freepik.com/premium-photo/electric-guitar-with-lighted-garland-dark-blue-background-gift-guitar-classic-shapes-christmas-new-year_431724-1660.jpg?w=740",
"https://www.superprof.it/blog/wp-content/uploads/2017/07/chuck-berry-chitarra.jpg.webp",
"https://open.spotify.com/artist/293zczrfYafIItmnmM3coR?si=CaD0hk91Q1mED3_ytQsDEA");